### ISSUE TITLE
 ERROR: Could not find a version that satisfies the requirement MEDIAR

### ISSUE THREAD

**Issue by rmd13** [Lee-Gihun/MEDIAR#10]
Hi, I am tring to intall MEDIAR into Anaconda3 using:
```
conda create --name Mediar python=3.8
conda activate Mediar
(base) C:\Users\rmd>conda activate Mediar
 (Mediar) C:\Users\rmd>python -m pip install MEDIAR
```
>
> ERROR: Could not find a version that satisfies the requirement MEDIAR (from vers
> ions: none)
> ERROR: No matching distribution found for MEDIAR

How can this be solved?
Thank you.

**Comment by Lee-Gihun** [comment]
The previous version of the our code contained numerous unusual package version mappings. I have now realigned these mappings. Please check again and reopen this issue if the problem recurs.
