### ISSUE TITLE
 Running the predict.py code does not produce segmentation results.

### ISSUE THREAD

**Issue by lzkzls** [Lee-Gihun/MEDIAR#14]
Hello, thank you for sharing the code. I used two images from the image/examples folder and ran the predict.py code, but the segmentation results I obtained are two completely black images. I replaced the images with my own cell images, but still obtained completely black images as results. Could you please advise on how to troubleshoot this issue?

>

**Comment by Lee-Gihun** [comment]
It is highly likely that you opened the file with a default image viewer in the OS (e.g., Windows). If you examine the internal values of the predicted labels in the `.tiff` files, you will find integer values, each corresponding to a unique cell.

Let me close this issue, and please reopen if the same problem still happens.
