### ISSUE TITLE
requirements.txt has package version "0.0" for skimage

### ISSUE THREAD

**Issue by awedwards** [Lee-Gihun/MEDIAR#15]
Hi! Looking forward to trying your software out on some data!

I am trying to install your codebase and noticed that the package version for `scikit-image` is 0.0, which seems incorrect? It's also called `skimage` in the requirements folder, which is the incorrect name of the package (should be `scikit-image`).

Thanks

**Comment by Lee-Gihun** [comment]
Oh, thank you for letting me know. The `skimage` package can be installed simply by using `pip install skimage`, as it does not depend on a specific version. I deleted it from the `requirement.txt`.
