### ISSUE TITLE
Please retain the Cellpose copyright as required by the BSD-3 license

### ISSUE THREAD

**Issue by marius10p** [Lee-Gihun/MEDIAR#17]
The Cellpose license (BSD-3) is very permissive. However, it requires you to retain the copyright notice [here](https://github.com/MouseLand/cellpose?tab=BSD-3-Clause-1-ov-file) when you copy portions of the code. 

All of the contents of [this library](https://github.com/Lee-Gihun/MEDIAR/blob/main/core/MEDIAR/utils.py) in your repository are copied over from the Cellpose dynamics library  [here](https://github.com/MouseLand/cellpose/blob/main/cellpose/dynamics.py) (primarily) or from the Cellpose utils and metrics libraries. The copyright notice must be maintained and distributed with every copy of your codebase (including in the napari plugin and in the docker image). 

In addition, we ask that you include this copyright statement at the top of  your file: 
"""
Copyright © 2022 Howard Hughes Medical Institute, Authored by Carsen Stringer and Marius Pachitariu.
"""

Thank you.

**Comment by Lee-Gihun** [comment]
Thank you for bringing this to our attention! While we did reference the original sources within our code, we acknowledge that we may not have fully complied with the required copyright protocols.

We have made a commit (78df966a9938ad477c151445cacc817947487e51) to address the changes you requested. Could you please review it to ensure it meets your requirements? We intend to update both the napari plugin and the docker image accordingly.

@joonkeekim, could you please ensure the copyright statement is included in both the napari plugin and the docker image as requested?

We will close this issue once the updates have been confirmed and implemented across all mentioned platforms.

**Comment by marius10p** [comment]
Thank you for the prompt response, much appreciated. I believe you have to keep the complete licence file, but let me double check with our IP advisers. Please reference the dynamics, utils and metrics libraries, since there is code here from all of those, though it's mostly from dynamics.

**Comment by marius10p** [comment]
I double checked quickly and it is indeed true, you should essentially reproduce the complete HHMI license, as specified in this line of the license:  

> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

**Comment by Lee-Gihun** [comment]
I included the complete HHMI license with the clarification of the reference sources.

To the best of my knowledge, it is allowed to add line breaks if the original content of the license is maintained. So, I made some line breaks for better readability.

Please check the commit c34aa0d1626567e678b62a0acb4464624328e291 and review whether this version follows the required copyright protocol.

**Comment by marius10p** [comment]
This looks good  to me, thanks @Lee-Gihun !

**Comment by Lee-Gihun** [comment]
Great! @joonkeekim, please reflect the changes in the Napari Plugin and Docker Image accordingly.

**Comment by joonkeekim** [comment]
@Lee-Gihun I have completed the notation of the HHMI license with the clarification of the reference sources in the new docker image and the Napari Plugin repository!
