### ISSUE TITLE
Access to data used for inference

### ISSUE THREAD

**Issue by jachou1** [Lee-Gihun/MEDIAR#2]
Hello,

I'm interested in using your model to segment cells in my data. However, I'd like to just run the prediction on your testing dataset. When I try to use the predict.py, it throws an error on not being able to find the data. Could you advise how to get access to the data and/or how I can use what you created for my own data? Thank you.

<img width="1206" alt="Screen Shot 2023-02-21 at 10 05 28 AM" src="https://user-images.githubusercontent.com/88116657/220381870-f64e4cd2-da53-4fa9-b53c-8fe376316634.png">

**Comment by Lee-Gihun** [comment]
The official challenge data is accessible at [https://neurips22-cellseg.grand-challenge.org/](https://neurips22-cellseg.grand-challenge.org/).
