### ISSUE TITLE
What is "classes" parameter in config?

### ISSUE THREAD

**Issue by mese79** [Lee-Gihun/MEDIAR#5]
Hi  
What does "classes" parameter in configs do? Is it about label classes like cell, background, and ?!
[classes in config](https://github.com/Lee-Gihun/MEDIAR/blob/594165779a10f7b65339929de72d0a5f9e0fbbde/config/step3_prediction/base_prediction.json#L16)

**Comment by Lee-Gihun** [comment]
`classes` config is the model-specific config. It decides the number of final output neurons of the fully-connected layer.

As cell segmentation is binary problem (0:bgd, 1:cell), we either use 1 or 2 neurons. We used a single neuron for the segmentation.

In the config file, you can see we set 3 for the `classes`. Here, the other two dimensions each stand for x-axis and y-axis gradient field. They predicts the relative position w.r.t. center of the cell center (median of h,w).

**Comment by Lee-Gihun** [comment]
Although we also mentioned in our paper as "Gradient Tracking" Sections, the act of how this tracking works is explained in more details at the [CellPose paper](https://www.biorxiv.org/content/10.1101/2020.02.02.931238v2.full). The gradient tracking parts [in our code](https://github.com/Lee-Gihun/MEDIAR/blob/main/core/MEDIAR/utils.py) is a refactored version of their official code.
