### ISSUE TITLE
MEDIAR package

### ISSUE THREAD

**Issue by pakiessling** [Lee-Gihun/MEDIAR#7]
Thank you for the tool!

Performance is very impressive on my data.

Have you thought about creating a MEDIAR package that people can use to segment their images?

I think this would make it easier to include this into segmentation pipelines without putting sys.path.insert everywhere

**Comment by Lee-Gihun** [comment]
Thank you for your interest and suggestion!

We're not have any specific plan for it, but let us consider :)
